name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
    permissions:
      contents: write # to generate release note
    steps:
      - uses: actions/checkout@v4
      - uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            cmake --preset mingw-w64-x86_64
            cmake --build build --target wineinfo
      - run: |
          cd build/VST3/Release
          zip -r ../../../wineinfo-${VERSION}.zip wineinfo.vst3
      - run: |
          gh release create "${VERSION}" --title "${VERSION}" --generate-notes
          gh release upload "${VERSION}" wineinfo-${VERSION}.zip
        env:
          GH_TOKEN: ${{ github.token }}
